name = "MobiusSphereVisual"
uuid = "23a7d53f-6290-4ab9-a41c-6427287ae7da"
authors = ["LauBMo <laurea987@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
FileIO = "1.17.0"
LinearAlgebra = "1.11.0"
Printf = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
